/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.farm {
    export class farmIndexsceneUI extends Laya.Scene {
		public farmbg_1:Laya.Sprite;
		public farmbg_2:Laya.Sprite;
		public building:Laya.Button;
		public n40:Laya.Sprite;
		public order:Laya.Button;
		public email:Laya.Button;
		public upgrade:Laya.Button;
		public top_kuan:Laya.Box;
		public kuan:Laya.Sprite;
		public uname_bg:Laya.Sprite;
		public uname:laya.display.Text;
		public bottom:Laya.Box;
		public botton_bg:Laya.Sprite;
		public main_btn_kuan:Laya.Box;
		public n26:Laya.Button;
		public main_btn:Laya.Button;
		public main_btn_txt:Laya.Sprite;
		public factory_kuan:Laya.Box;
		public factory_btn:Laya.Button;
		public factory_btn_txt:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/farmIndexscene");
        }
    }
    REG("ui.farm.farmIndexsceneUI",farmIndexsceneUI);
    export class farmLandUI extends Laya.Scene {
		public land:Laya.Sprite;
		public xuanzhong:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/farmLand");
        }
    }
    REG("ui.farm.farmLandUI",farmLandUI);
}
export module ui.login {
    export class loginUI extends Laya.Scene {
		public n10:Laya.Sprite;
		public n11:Laya.Sprite;
		public loading_group:Laya.Box;
		public loading_icon:Laya.Sprite;
		public loading_txt:laya.display.Text;
		public login_group:Laya.Box;
		public login_check:Laya.Button;
		public n6:laya.display.Text;
		public login_btn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("login/login");
        }
    }
    REG("ui.login.loginUI",loginUI);
}