/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.base {
    export class tishi_tipUI extends Laya.Dialog {
		public tip_bg:Laya.Sprite;
		public close_btn:Laya.Button;
		public content_txt:laya.display.Text;
		public confirm_btn:Laya.Button;
		public cancel_btn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("base/tishi_tip");
        }
    }
    REG("ui.base.tishi_tipUI",tishi_tipUI);
}
export module ui.farm {
    export class farmIndexsceneUI extends Laya.Scene {
		public farmbg_1:Laya.Sprite;
		public farmbg_2:Laya.Sprite;
		public building:Laya.Button;
		public n40:Laya.Sprite;
		public order:Laya.Button;
		public email:Laya.Button;
		public upgrade:Laya.Button;
		public top_kuan:Laya.Box;
		public kuan:Laya.Sprite;
		public uname_bg:Laya.Sprite;
		public uname:laya.display.Text;
		public bottom:Laya.Box;
		public botton_bg:Laya.Sprite;
		public main_btn_kuan:Laya.Box;
		public n26:Laya.Button;
		public main_btn:Laya.Button;
		public main_btn_txt:Laya.Sprite;
		public factory_kuan:Laya.Box;
		public factory_btn:Laya.Button;
		public factory_btn_txt:Laya.Sprite;
		public bg_kuan:Laya.Box;
		public n71:Laya.Sprite;
		public n72:Laya.Sprite;
		public n74:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/farmIndexscene");
        }
    }
    REG("ui.farm.farmIndexsceneUI",farmIndexsceneUI);
    export class farmLandUI extends Laya.Scene {
		public land:Laya.Image;
		public xuanzhong:Laya.Image;
		public flower:Laya.Image;
		public extend_btn:Laya.Button;
		public extend_kuan:Laya.Box;
		public n14:Laya.Sprite;
		public extend_gold:laya.display.Text;
		public upgrade_kuan:Laya.Box;
		public n17:Laya.Image;
		public n18:Laya.Sprite;
		public upgrade_gold:laya.display.Text;
		public upgrade_info:Laya.TextArea;
		public upgrade_progressbar:Laya.ProgressBar;
		public upgrade_level:laya.display.Text;
		public grow_kuan:Laya.Box;
		public n24:laya.display.Text;
		public grow_time_val:Laya.ProgressBar;
		public grow_time:laya.display.Text;
		public fertilizer_kuan:Laya.Box;
		public n27:laya.display.Text;
		public fertilizer_time_val:Laya.ProgressBar;
		public fertilizer_time:laya.display.Text;
		public harvest_icon:Laya.Sprite;
		public water_icon:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/farmLand");
        }
    }
    REG("ui.farm.farmLandUI",farmLandUI);
    export class itemUI extends Laya.Scene {
		public n0:Laya.Image;
		public seep_pic:Laya.Sprite;
		public n2:Laya.Image;
		public n3:Laya.Sprite;
		public gold:laya.display.Text;
		public suo_div:Laya.Box;
		public n4:Laya.Image;
		public n5:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/item");
        }
    }
    REG("ui.farm.itemUI",itemUI);
    export class seedListUI extends Laya.Scene {
		public n1:Laya.Image;
		public seed_list:Laya.List;
		public seed_item:Laya.Box;
		public n9:Laya.Image;
		public seep_pic:Laya.Image;
		public n2:Laya.Image;
		public n3:Laya.Sprite;
		public gold_num:Laya.Label;
		public suo_div:Laya.Box;
		public n4:Laya.Image;
		public n5:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("farm/seedList");
        }
    }
    REG("ui.farm.seedListUI",seedListUI);
}
export module ui.login {
    export class loginUI extends Laya.Scene {
		public n10:Laya.Sprite;
		public n11:Laya.Sprite;
		public loading_group:Laya.Box;
		public loading_icon:Laya.Sprite;
		public loading_txt:laya.display.Text;
		public login_group:Laya.Box;
		public login_check:Laya.Button;
		public n6:laya.display.Text;
		public login_btn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("login/login");
        }
    }
    REG("ui.login.loginUI",loginUI);
}
export module ui.warehouse {
    export class good_itemUI extends Laya.Scene {
		public n2:Laya.Sprite;
		public gicon:Laya.Sprite;
		public gnum:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("warehouse/good_item");
        }
    }
    REG("ui.warehouse.good_itemUI",good_itemUI);
    export class sell_tipUI extends Laya.Scene {
		public n0:Laya.Image;
		public close_btn:Laya.Button;
		public jian_btn:Laya.Button;
		public jia_btn:Laya.Button;
		public gname:laya.display.Text;
		public n7:Laya.Sprite;
		public sell_btn:Laya.Button;
		public tot_price:laya.display.Text;
		public n14:Laya.Sprite;
		public gicon:Laya.Sprite;
		public tot_num:laya.display.Text;
		public gdescribe:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("warehouse/sell_tip");
        }
    }
    REG("ui.warehouse.sell_tipUI",sell_tipUI);
    export class warehouseUI extends Laya.Scene {
		public n0:Laya.Sprite;
		public n3:Laya.Sprite;
		public good_num:laya.display.Text;
		public n5:laya.display.Text;
		public n6:laya.display.Text;
		public close_btn:Laya.Button;
		public upgrade_btn:Laya.Button;
		public n10:Laya.Image;
		public item_title_div:Laya.Box;
		public item_all:Laya.Button;
		public item_all_biao:Laya.Sprite;
		public item_flower:Laya.Button;
		public item_flower_biao:Laya.Sprite;
		public item_good:Laya.Button;
		public item_good_biao:Laya.Sprite;
		public good_list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("warehouse/warehouse");
        }
    }
    REG("ui.warehouse.warehouseUI",warehouseUI);
}